apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  selector:
    matchLabels:
      app: capstone-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
